# Generated by Django 6.0.3 on 2026-03-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_seed_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invitation', '会议邀请'), ('reminder', '会议提醒'), ('update', '会议更新'), ('cancellation', '会议取消')], max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('status', models.CharField(choices=[('unread', '未读'), ('read', '已读'), ('dismissed', '已忽略')], default='unread', max_length=20, verbose_name='状态')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划发送时间')),
                ('sent_time', models.DateTimeField(blank=True, null=True, verbose_name='实际发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app1.meeting', verbose_name='相关会议')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_methods', models.JSONField(default=list, verbose_name='提醒方式')),
                ('default_reminder_minutes', models.JSONField(default=[15, 60], verbose_name='默认提前时间(分钟)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='应用内通知')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='短信通知')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提醒设置',
                'verbose_name_plural': '提醒设置',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pending', '待回复'), ('accepted', '已接受'), ('declined', '已拒绝')], default='pending', max_length=20, verbose_name='回复状态')),
                ('response_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('is_required', models.BooleanField(default=True, verbose_name='必须参加')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='app1.meeting', verbose_name='会议')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='app1.person', verbose_name='参与人')),
            ],
            options={
                'verbose_name': '会议参与人',
                'verbose_name_plural': '会议参与人',
                'ordering': ['-added_at'],
                'unique_together': {('meeting', 'person')},
            },
        ),
    ]
