# Generated by Django 6.0.3 on 2026-03-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_meetingattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事项')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('finished', '已结束')], default='not_started', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='app1.meeting', verbose_name='会议')),
            ],
            options={
                'verbose_name': '会议事项',
                'verbose_name_plural': '会议事项',
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAgendaItemAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='app1.meetingagendaitem', verbose_name='会议事项')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_item_assignments', to='app1.person', verbose_name='人员')),
            ],
            options={
                'verbose_name': '会议事项人员',
                'verbose_name_plural': '会议事项人员',
                'ordering': ['person__name'],
                'unique_together': {('agenda_item', 'person')},
            },
        ),
    ]
