# Generated by Django 6.0.3 on 2026-04-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_meetingagendaitem_meetingagendaitemassignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved_pending', '审批通过未开始'), ('in_progress', '进行中'), ('done', '已结束'), ('expired_cancelled', '未审批过期已取消'), ('rejected', '审批未通过')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
